### ISSUE TITLE
Admin: Create default User Story template

### ISSUE THREAD

**Issue by davewatters** [hashim222/save-earth#8]
User story template should have structure similar to this.. just an example..
(copied from my own user-story--.md)
<hr>
---
name: User Story
about: User Story Template
title: 'User Story: '
labels: ''
assignees: ''

---

As a **user** I can **capability** so that I **received-benefit**

### Acceptance Criteria
- User role should be able to <do_this_thing> 
- 
- 

### Tasks
- [ ] This is a task to undertake to achieve <the_thing>
- [ ] This functionality must also be coded to complete this story

**Comment by auxfuse** [comment]
Some user stories will be defined in README
